spring:
  datasource:
   druid:
     driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://39.108.172.148:8096/PMDB?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
     url: jdbc:mysql://localhost:3306/pmdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
     username: root
     password: root
#     url: jdbc:mysql://112.74.35.114:8066/PMDB?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#     url: jdbc:mysql://112.74.35.114:3306/PmShelter?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#     username: puming
#     password: Puming888!
     initial-size: 5
     max-active: 20
     min-idle: 10
     max-wait: 5000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1
     testWhileIdle: true
     testOnBorrow: true
     testOnReturn: false
     filters: stat,wall,log4j
     filter:
       stat:
         log-slow-sql: true
         slow-sql-millis: 2000

mybatis:
  type-aliases-package: com.pm.mc.pojo
  configuration:
    mapUnderscoreToCamelCase: true

mapper:
  mappers: com.pm.handle.utils.PmMapper
  not-empty: false
  identity: MYSQL

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

netty:
  port: 10012

websocket:
  port: 10013



